name: coffee_app_ui
description: "A new Flutter project."

publish_to: 'none'


version: 1.1.2+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  blurrycontainer: ^2.1.0
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  extended_image: ^9.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/design/design-reference.jpg
    - assets/images/start-decore.png
    - assets/images/cappuccino-one.png
    - assets/images/cappuccino-two.png
    - assets/images/iced-americano.png
    - assets/images/espresso-cup.png
    - assets/images/special-offer.png
    - assets/SVGs/
    - assets/SVGs/cappuccino-icon.svg
    - assets/SVGs/cold-brew-icon.svg
    - assets/SVGs/espresso-icon.svg
    - assets/SVGs/bell-icon.svg
    - assets/SVGs/filter-icon.svg
    - assets/SVGs/star-icon.svg
    - assets/SVGs/fire-emoji.png
    

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf

    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: Gidole
      fonts:
        - asset: assets/fonts/Gidole-Regular.ttf

